/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarCertificadoCodigoRouteImport } from './routes/validar-certificado.$codigo'
import { Route as TrilhasSlugRouteImport } from './routes/trilhas.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedEvolucaoRouteImport } from './routes/_authenticated/evolucao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCertificadosIndexRouteImport } from './routes/_authenticated/certificados.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedQuizModuleIdRouteImport } from './routes/_authenticated/quiz.$moduleId'
import { Route as AuthenticatedCursoSlugRouteImport } from './routes/_authenticated/curso.$slug'
import { Route as AuthenticatedCertificadosIdRouteImport } from './routes/_authenticated/certificados.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTrilhasRouteImport } from './routes/_authenticated/admin/trilhas'
import { Route as AuthenticatedAdminSenhaRouteImport } from './routes/_authenticated/admin/senha'
import { Route as AuthenticatedAdminQuestoesRouteImport } from './routes/_authenticated/admin/questoes'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin/pagamentos'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin/modulos'
import { Route as AuthenticatedAdminGerarCursoRouteImport } from './routes/_authenticated/admin/gerar-curso'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin/cursos'
import { Route as AuthenticatedAdminCertificadosRouteImport } from './routes/_authenticated/admin/certificados'
import { Route as AuthenticatedAdminAiStudioRouteImport } from './routes/_authenticated/admin/ai-studio'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'

const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarCertificadoCodigoRoute =
  ValidarCertificadoCodigoRouteImport.update({
    id: '/validar-certificado/$codigo',
    path: '/validar-certificado/$codigo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrilhasSlugRoute = TrilhasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrilhasRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvolucaoRoute = AuthenticatedEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosIndexRoute =
  AuthenticatedCertificadosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCertificadosRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedQuizModuleIdRoute =
  AuthenticatedQuizModuleIdRouteImport.update({
    id: '/quiz/$moduleId',
    path: '/quiz/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursoSlugRoute = AuthenticatedCursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosIdRoute =
  AuthenticatedCertificadosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCertificadosRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrilhasRoute =
  AuthenticatedAdminTrilhasRouteImport.update({
    id: '/trilhas',
    path: '/trilhas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSenhaRoute = AuthenticatedAdminSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminQuestoesRoute =
  AuthenticatedAdminQuestoesRouteImport.update({
    id: '/questoes',
    path: '/questoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulosRoute =
  AuthenticatedAdminModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGerarCursoRoute =
  AuthenticatedAdminGerarCursoRouteImport.update({
    id: '/gerar-curso',
    path: '/gerar-curso',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCertificadosRoute =
  AuthenticatedAdminCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiStudioRoute =
  AuthenticatedAdminAiStudioRouteImport.update({
    id: '/ai-studio',
    path: '/ai-studio',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRoute
  '/empresas': typeof EmpresasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/trilhas': typeof TrilhasRouteWithChildren
  '/turmas': typeof TurmasRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/validar-certificado/$codigo': typeof ValidarCertificadoCodigoRoute
  '/admin/ai-studio': typeof AuthenticatedAdminAiStudioRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/gerar-curso': typeof AuthenticatedAdminGerarCursoRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/questoes': typeof AuthenticatedAdminQuestoesRoute
  '/admin/senha': typeof AuthenticatedAdminSenhaRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/certificados/$id': typeof AuthenticatedCertificadosIdRoute
  '/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/certificados/': typeof AuthenticatedCertificadosIndexRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRoute
  '/empresas': typeof EmpresasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/trilhas': typeof TrilhasRouteWithChildren
  '/turmas': typeof TurmasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/validar-certificado/$codigo': typeof ValidarCertificadoCodigoRoute
  '/admin/ai-studio': typeof AuthenticatedAdminAiStudioRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/gerar-curso': typeof AuthenticatedAdminGerarCursoRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/questoes': typeof AuthenticatedAdminQuestoesRoute
  '/admin/senha': typeof AuthenticatedAdminSenhaRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/certificados/$id': typeof AuthenticatedCertificadosIdRoute
  '/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/certificados': typeof AuthenticatedCertificadosIndexRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cursos': typeof CursosRoute
  '/empresas': typeof EmpresasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/trilhas': typeof TrilhasRouteWithChildren
  '/turmas': typeof TurmasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evolucao': typeof AuthenticatedEvolucaoRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/validar-certificado/$codigo': typeof ValidarCertificadoCodigoRoute
  '/_authenticated/admin/ai-studio': typeof AuthenticatedAdminAiStudioRoute
  '/_authenticated/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin/gerar-curso': typeof AuthenticatedAdminGerarCursoRoute
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/questoes': typeof AuthenticatedAdminQuestoesRoute
  '/_authenticated/admin/senha': typeof AuthenticatedAdminSenhaRoute
  '/_authenticated/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/certificados/$id': typeof AuthenticatedCertificadosIdRoute
  '/_authenticated/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/_authenticated/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/certificados/': typeof AuthenticatedCertificadosIndexRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cursos'
    | '/empresas'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/trilhas'
    | '/turmas'
    | '/admin'
    | '/certificados'
    | '/dashboard'
    | '/evolucao'
    | '/profile'
    | '/trilhas/$slug'
    | '/validar-certificado/$codigo'
    | '/admin/ai-studio'
    | '/admin/certificados'
    | '/admin/cursos'
    | '/admin/gerar-curso'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/questoes'
    | '/admin/senha'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/certificados/$id'
    | '/curso/$slug'
    | '/quiz/$moduleId'
    | '/admin/'
    | '/certificados/'
    | '/api/public/webhooks/asaas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cursos'
    | '/empresas'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/trilhas'
    | '/turmas'
    | '/dashboard'
    | '/evolucao'
    | '/profile'
    | '/trilhas/$slug'
    | '/validar-certificado/$codigo'
    | '/admin/ai-studio'
    | '/admin/certificados'
    | '/admin/cursos'
    | '/admin/gerar-curso'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/questoes'
    | '/admin/senha'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/certificados/$id'
    | '/curso/$slug'
    | '/quiz/$moduleId'
    | '/admin'
    | '/certificados'
    | '/api/public/webhooks/asaas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cursos'
    | '/empresas'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/trilhas'
    | '/turmas'
    | '/_authenticated/admin'
    | '/_authenticated/certificados'
    | '/_authenticated/dashboard'
    | '/_authenticated/evolucao'
    | '/_authenticated/profile'
    | '/trilhas/$slug'
    | '/validar-certificado/$codigo'
    | '/_authenticated/admin/ai-studio'
    | '/_authenticated/admin/certificados'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/gerar-curso'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/questoes'
    | '/_authenticated/admin/senha'
    | '/_authenticated/admin/trilhas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/certificados/$id'
    | '/_authenticated/curso/$slug'
    | '/_authenticated/quiz/$moduleId'
    | '/_authenticated/admin/'
    | '/_authenticated/certificados/'
    | '/api/public/webhooks/asaas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CursosRoute: typeof CursosRoute
  EmpresasRoute: typeof EmpresasRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InscricaoRoute: typeof InscricaoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TrilhasRoute: typeof TrilhasRouteWithChildren
  TurmasRoute: typeof TurmasRoute
  ValidarCertificadoCodigoRoute: typeof ValidarCertificadoCodigoRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar-certificado/$codigo': {
      id: '/validar-certificado/$codigo'
      path: '/validar-certificado/$codigo'
      fullPath: '/validar-certificado/$codigo'
      preLoaderRoute: typeof ValidarCertificadoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$slug': {
      id: '/trilhas/$slug'
      path: '/$slug'
      fullPath: '/trilhas/$slug'
      preLoaderRoute: typeof TrilhasSlugRouteImport
      parentRoute: typeof TrilhasRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao': {
      id: '/_authenticated/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AuthenticatedEvolucaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados/': {
      id: '/_authenticated/certificados/'
      path: '/'
      fullPath: '/certificados/'
      preLoaderRoute: typeof AuthenticatedCertificadosIndexRouteImport
      parentRoute: typeof AuthenticatedCertificadosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/quiz/$moduleId': {
      id: '/_authenticated/quiz/$moduleId'
      path: '/quiz/$moduleId'
      fullPath: '/quiz/$moduleId'
      preLoaderRoute: typeof AuthenticatedQuizModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$slug': {
      id: '/_authenticated/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof AuthenticatedCursoSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados/$id': {
      id: '/_authenticated/certificados/$id'
      path: '/$id'
      fullPath: '/certificados/$id'
      preLoaderRoute: typeof AuthenticatedCertificadosIdRouteImport
      parentRoute: typeof AuthenticatedCertificadosRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trilhas': {
      id: '/_authenticated/admin/trilhas'
      path: '/trilhas'
      fullPath: '/admin/trilhas'
      preLoaderRoute: typeof AuthenticatedAdminTrilhasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/senha': {
      id: '/_authenticated/admin/senha'
      path: '/senha'
      fullPath: '/admin/senha'
      preLoaderRoute: typeof AuthenticatedAdminSenhaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questoes': {
      id: '/_authenticated/admin/questoes'
      path: '/questoes'
      fullPath: '/admin/questoes'
      preLoaderRoute: typeof AuthenticatedAdminQuestoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gerar-curso': {
      id: '/_authenticated/admin/gerar-curso'
      path: '/gerar-curso'
      fullPath: '/admin/gerar-curso'
      preLoaderRoute: typeof AuthenticatedAdminGerarCursoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/certificados': {
      id: '/_authenticated/admin/certificados'
      path: '/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AuthenticatedAdminCertificadosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai-studio': {
      id: '/_authenticated/admin/ai-studio'
      path: '/ai-studio'
      fullPath: '/admin/ai-studio'
      preLoaderRoute: typeof AuthenticatedAdminAiStudioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiStudioRoute: typeof AuthenticatedAdminAiStudioRoute
  AuthenticatedAdminCertificadosRoute: typeof AuthenticatedAdminCertificadosRoute
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminGerarCursoRoute: typeof AuthenticatedAdminGerarCursoRoute
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminQuestoesRoute: typeof AuthenticatedAdminQuestoesRoute
  AuthenticatedAdminSenhaRoute: typeof AuthenticatedAdminSenhaRoute
  AuthenticatedAdminTrilhasRoute: typeof AuthenticatedAdminTrilhasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiStudioRoute: AuthenticatedAdminAiStudioRoute,
    AuthenticatedAdminCertificadosRoute: AuthenticatedAdminCertificadosRoute,
    AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
    AuthenticatedAdminGerarCursoRoute: AuthenticatedAdminGerarCursoRoute,
    AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRoute,
    AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
    AuthenticatedAdminQuestoesRoute: AuthenticatedAdminQuestoesRoute,
    AuthenticatedAdminSenhaRoute: AuthenticatedAdminSenhaRoute,
    AuthenticatedAdminTrilhasRoute: AuthenticatedAdminTrilhasRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCertificadosRouteChildren {
  AuthenticatedCertificadosIdRoute: typeof AuthenticatedCertificadosIdRoute
  AuthenticatedCertificadosIndexRoute: typeof AuthenticatedCertificadosIndexRoute
}

const AuthenticatedCertificadosRouteChildren: AuthenticatedCertificadosRouteChildren =
  {
    AuthenticatedCertificadosIdRoute: AuthenticatedCertificadosIdRoute,
    AuthenticatedCertificadosIndexRoute: AuthenticatedCertificadosIndexRoute,
  }

const AuthenticatedCertificadosRouteWithChildren =
  AuthenticatedCertificadosRoute._addFileChildren(
    AuthenticatedCertificadosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvolucaoRoute: typeof AuthenticatedEvolucaoRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCursoSlugRoute: typeof AuthenticatedCursoSlugRoute
  AuthenticatedQuizModuleIdRoute: typeof AuthenticatedQuizModuleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvolucaoRoute: AuthenticatedEvolucaoRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCursoSlugRoute: AuthenticatedCursoSlugRoute,
  AuthenticatedQuizModuleIdRoute: AuthenticatedQuizModuleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TrilhasRouteChildren {
  TrilhasSlugRoute: typeof TrilhasSlugRoute
}

const TrilhasRouteChildren: TrilhasRouteChildren = {
  TrilhasSlugRoute: TrilhasSlugRoute,
}

const TrilhasRouteWithChildren =
  TrilhasRoute._addFileChildren(TrilhasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CursosRoute: CursosRoute,
  EmpresasRoute: EmpresasRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InscricaoRoute: InscricaoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TrilhasRoute: TrilhasRouteWithChildren,
  TurmasRoute: TurmasRoute,
  ValidarCertificadoCodigoRoute: ValidarCertificadoCodigoRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
